---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - infra.mkz.me
  resources:
  - nodelabels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infra.mkz.me
  resources:
  - nodelabels/finalizers
  verbs:
  - update
- apiGroups:
  - infra.mkz.me
  resources:
  - nodelabels/status
  verbs:
  - get
  - patch
  - update
